name: Build SPDK

on:
  push:
    branches: [master, '**']
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential \
            git \
            pkg-config \
            libaio-dev \
            libnuma-dev \
            libssl-dev \
            uuid-dev \
            liburing-dev \
            python3 \
            python3-pip
            ninja-build
            python3-tabulate

      - name: Install meson
        run: pip3 install meson
            # libfuse-dev

      - name: Configure
        run: ./configure --without-nvme-cuse

      - name: Build
        run: make -j$(nproc)

      - name: Run unit tests
        run: ./test/unit/unittest.sh
